export class User {
    // i added the user id field cuz i use it to disable user account (check manage-users.component.ts)
    id?:number;
    password?:string;
    email?:string;
    firstname?:string;
    lastname?:string;
    status?:string;
    role?:string;
    clear()
    {
        this.id=null;
        this.password="";
        this.email="";
        this.lastname="";
        this.firstname="";
        this.status="";
        this.role="";
    }
    toJson()
    {
        return 
        {
            this.id,
            this.password,
            this.email,
            this.lastname,
            this.firstname,
            this.status,
            this.role
        }
    }
}